In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.optimizers import Adam

from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model


In [14]:
data = pd.read_csv('iris.data')
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [15]:
data['Iris-setosa'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        49
Name: Iris-setosa, dtype: int64

In [21]:
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values


In [22]:
# y = pd.get_dummies(y)


In [23]:
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [25]:
model = Sequential()
model.add(Dense(4,input_shape=(4,),activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=10, nb_epoch=100)



C:\Users\Shrikant\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """


Epoch 1/100
119/119 [==============================] - 0s 4ms/step - loss: 1.4370 - acc: 0.1345
Epoch 2/100
119/119 [==============================] - 0s 245us/step - loss: 1.3880 - acc: 0.0756
Epoch 3/100
119/119 [==============================] - 0s 279us/step - loss: 1.3348 - acc: 0.0504
Epoch 4/100
119/119 [==============================] - 0s 232us/step - loss: 1.2814 - acc: 0.1092
Epoch 5/100
119/119 [==============================] - 0s 266us/step - loss: 1.2289 - acc: 0.1933
Epoch 6/100
119/119 [==============================] - 0s 279us/step - loss: 1.1792 - acc: 0.3109
Epoch 7/100
119/119 [==============================] - 0s 249us/step - loss: 1.1422 - acc: 0.3445
Epoch 8/100
119/119 [==============================] - 0s 171us/step - loss: 1.1155 - acc: 0.3529
Epoch 9/100
119/119 [==============================] - 0s 297us/step - loss: 1.0956 - acc: 0.3529
Epoch 10/100
119/119 [==============================] - 0s 188us/step - loss: 1.0837 - acc: 0.3529
Epoch 11/100
119/119 

119/119 [==============================] - 0s 220us/step - loss: 0.6543 - acc: 0.7059
Epoch 84/100
119/119 [==============================] - 0s 197us/step - loss: 0.6512 - acc: 0.7059
Epoch 85/100
119/119 [==============================] - 0s 220us/step - loss: 0.6477 - acc: 0.7059
Epoch 86/100
119/119 [==============================] - 0s 139us/step - loss: 0.6445 - acc: 0.7059
Epoch 87/100
119/119 [==============================] - 0s 212us/step - loss: 0.6415 - acc: 0.7143
Epoch 88/100
119/119 [==============================] - 0s 196us/step - loss: 0.6383 - acc: 0.7143
Epoch 89/100
119/119 [==============================] - 0s 131us/step - loss: 0.6353 - acc: 0.7143
Epoch 90/100
119/119 [==============================] - ETA: 0s - loss: 0.6039 - acc: 0.800 - 0s 174us/step - loss: 0.6323 - acc: 0.7059
Epoch 91/100
119/119 [==============================] - 0s 161us/step - loss: 0.6297 - acc: 0.7143
Epoch 92/100
119/119 [==============================] - 0s 117us/step - loss: 0.6269

In [26]:
y_pred = model.predict(X_test)

In [28]:
import numpy as np
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)


In [29]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.20      0.33        10
           2       0.50      1.00      0.67         8

   micro avg       0.73      0.73      0.73        30
   macro avg       0.83      0.73      0.67        30
weighted avg       0.87      0.73      0.69        30

[[12  0  0]
 [ 0  2  8]
 [ 0  0  8]]
